### ISSUE TITLE
Visualization of tile IDs

### ISSUE THREAD

**Issue by dorkster** [flareteam/flare-game#516]
_I don't think I've shared this before, but I figure it may be helpful to other modders out there._

When creating maps, it's useful to know the numerical tile IDs of various tiles when creating events with `mapmod` components. To make this easier for myself, I've created a rough Bash [script](https://gist.github.com/dorkster/76244c7ccecf84ce71b2f488715c4da8) that will use ImageMagick to generate a version of the tileset with an overlay of tile IDs.

Here's an example using the dungeon tileset:

![tileset_dungeon_overlay](https://cloud.githubusercontent.com/assets/913982/17280139/b48c04a2-5756-11e6-950c-f666283030f1.png)

**Comment by LordStephen77** [comment]
Extremely useful! in the future, it would be very nice to see the tiles of the directly in-game tiles (example: F10 debug mode key and ID view of the mouse pointer to the game map). Good idea :)

**Comment by dorkster** [comment]
For future reference:

- This script isn't really needed any more. It's possible to edit `mapmod` properties easily in Tiled with the [flare-tiled-tools](https://github.com/flareteam/flare-tiled-tools) extension.
- It's been possible for a while now to inspect tiles in-game with the dev console open. Right-clicking on a tile will print information about it in the console.
