### ISSUE TITLE
Feature request: allow accessing Preferences from game

### ISSUE THREAD

**Issue by vgaming** [flareteam/flare-game#690]
This could be useful if you want to override keyboard settings while remaining in-game.

Thoughts?

**Comment by dorkster** [comment]
This is a tricky one, as some of the config options require the re-creation of some parts of game state.

I think what needs to happen first is a refactor of the config menu. Ideally, we want to be able to individually lock or hide different options depending on the context. Such a setup is also desirable for platforms that use a complex combination of options. As of now, we only have it split between desktop and non-desktop options.

**Comment by dorkster** [comment]
This was implemented back in version 1.10.

**Comment by vgaming** [comment]
@dorkster I see it's indeed working now! Niice, thanks!
