### ISSUE TITLE
Don't use self-signed certificates on the web site, just get a free one from Let's Encrypt

### ISSUE THREAD

**Issue by KOLANICH** [flareteam/flare-game#716]

**Comment by dorkster** [comment]
According to @clintbellanger, our server is old and not supported by Let's Encrypt, so we just went with a self-signed cert when setting up the new website.

**Comment by tvleavitt** [comment]
How old is our server? What are we running? I'm a sysadmin with 25 years of experience, and would be happy to look at the situation.

**Comment by dorkster** [comment]
Not sure what specifically is required for Let's Encrypt. Our server's kernel version is `2.6.32-028stab118.1`, to give you an idea of age.

**Comment by tvleavitt** [comment]
Eep... that's pretty dang old. What's the obstacle to running something more current?

**Comment by clintbellanger** [comment]
That's the version that comes with the VM we're using on our hosting (vps at godaddy), we just reimaged the server last month. We can probably upgrade it in place though, the whole VM is ours. It's on old Fedora.

**Comment by tvleavitt** [comment]
Hmm... why Fedora and not CentOS, if you're going with RedHat distributions? I have a Godaddy VPS running CentOS for a client. Fedora's primarily a desktop / development OS, with a fairly rapid release cycle. I'm honestly not familiar with the risks / mechanics of upgrading recent Fedora releases in place, my preference for server side installations at this point is Ubuntu LTS. Based on the page below, vs. what release you're actually running, there's a variety of approaches to take. But, given the various recent global security issues that have emerged, running a current, supported release is strongly encouraged.

I'd be willing to take a look at what an in place upgrade would involve, although it might actually be easier to just migrate the content to a new OS install if the website isn't particularly complex.

https://fedoraproject.org/wiki/Upgrading
