### ISSUE TITLE
The Locked Out Quest

### ISSUE THREAD

**Issue by Simon-Charest** [flareteam/flare-game#783]
For some reason, I was able to start the Locked Out quest, talk to Aldwulf, go back to the Goblin Camp, get the key, go back to Stormrock Ruins and open the locked door.

But I was never able to meet with Aldwulf again. I can only find a skeleton where he was at. The door in Stormrock Ruins stays unlocked, there is no entry in my Quests Log at all and Aldwulf is nowhere to be found. There might be an issue with that quest. It might have to do with using the Save & Exit feature while the quest in ongoing. I couldn't pinpoint the between which two steps exactly though.

Note: I have finished the game and all of the other 11 quests.

It may concern one of the following files:
- C:\Program Files (x86)\Flare\mods\empyrean_campaign\maps\goblin_camp.txt
- C:\Program Files (x86)\Flare\mods\empyrean_campaign\maps\stormrock_ruins.txt
- C:\Program Files (x86)\Flare\mods\empyrean_campaign\npcs\aldwulf.txt
- C:\Program Files (x86)\Flare\mods\empyrean_campaign\quests\006_stormrock.txt
- C:\Program Files (x86)\Flare\mods\empyrean_campaign\scripts\reset_stormrock.txt

**Comment by Simon-Charest** [comment]
Tip: I use these commands under the Command Prompt to help me search the text files' content:
- cd C:\Program Files (x86)\Flare
- cls & findstr /s "Aldwulf" *.txt
- cls & findstr /s "Locked Out" *.txt

**Comment by dorkster** [comment]
This is not a bug. The implication is that Aldwulf dies to the Antlion Burster near his corpse. You can use the key to open the locked door (completing the quest) and explore the ruins yourself.

**Comment by Simon-Charest** [comment]
Ok, so the bug is simply that the game is not keeping the "Locked Out" entry in the Quest Log then.

I only have the other 11 Completed Quests.

**Comment by dorkster** [comment]
Oh you're right. Fixed here: https://github.com/flareteam/flare-game/commit/9dc2143a6be875bfc7206ac57252b9550635a08b

**Comment by Simon-Charest** [comment]
Thanks!
