### ISSUE TITLE
Cardinal directions

### ISSUE THREAD

**Issue by Simon-Charest** [flareteam/flare-game#785]
The four cardinal directions (N, E, S, and W) should be added to the minimap.

**Comment by dorkster** [comment]
Good idea. I've had to explain which way North was in the past.

**Comment by dorkster** [comment]
Implemented: https://github.com/flareteam/flare-engine/commit/c21f638a951272f23356a98abaefc33257301d99

I've opted for using compass images instead of text labels. A compass is less translation overhead, and it just looks nicer in my opinion.
