### ISSUE TITLE
Holding Bow and Sword

### ISSUE THREAD

**Issue by Simon-Charest** [flareteam/flare-game#787]
I find it kind of funny that a character can carry a melee weapon in his main hand and a ranged weapon in his off hand, can receive both weapons' bonuses, and can attack with both but cannot wear and shield and a ranged weapon at the same time, which would make a little more sense...

**Comment by dorkster** [comment]
While this was fixed in the Empyrean Campaign, this change never made it to the Alpha Demo. We wanted to maintain its gameplay, unbalanced or otherwise.

**Comment by clintbellanger** [comment]
Some of these are artifacts from really old design ideas/choices.

The original main attributes were physical vs mental and offense vs defense.
These corresponded to sword vs staff (right hand carry) and bow vs shield (left hand carry).

I liked the idea of opposing main attributes and low level caps to encourage players to specialize one way or the other.
