### ISSUE TITLE
Click location to go

### ISSUE THREAD

**Issue by q3cpma** [flareteam/flare-game#789]
Hello, I was wondering if this was possible to click somewhere for your character to go (maybe with path finding too) since I find it tiring to always maintain the left mouse button to move.

**Comment by McSinyx** [comment]
Hi there, the algorithm (flood fill/forest fire) is quite simple to implement, though I'm not sure how to inject that in the game. I'd like to help if there's anything I can do.

**Comment by dorkster** [comment]
I wasn't describing a technical limitation. We have A* pathfinding in the engine, but I find steering the player in the absolute direction of the cursor more comfortable. Yet the click-once scheme doesn't really work well without pathfinding, so I opted for hold-to-move.
