### ISSUE TITLE
Key of Stormrock Ruins

### ISSUE THREAD

**Issue by Scriptura** [flareteam/flare-game#797]
Hello. I discovered your game a few days ago. I find it interesting, but I have a problem: I am stuck because I can not pass the level of Stormrock Ruins. I can not find the key that is supposed to be south of the ruins (so bottom left of the map Stormrock Pass if I understand correctly). Where is this key? In advance, thank you.

**Comment by dorkster** [comment]
The quest text mentions the key being in a camp to the south of *Stonewood*, which is a different map. You should be ablt to return to Stonewood via a Hyperspace teleporter. 

The map to the south of Stonewood is the Goblin Camp. The key is in this area.

**Comment by Scriptura** [comment]
Indeed! English is not my language and my effort to translate the instruction made me lose sight of the importance of place names. Thank you.

**Comment by nerozero** [comment]
Hi there, I have several times entered StoneWood, found camp but stoll - no key (v1.14)

**Comment by nerozero** [comment]
Never mind, found it
