### ISSUE TITLE
it's possible to kill Vohn in a close loop (zombie boss at Torture Chambers)

### ISSUE THREAD

**Issue by vgaming** [flareteam/flare-game#798]
If you just finish the maze level, and go to the next level, your saving point would be the end of the maze. You can then enable all mana-related buffs, and go fight with the zombie -- it's very easy. If the zombie (Vohn) won't have a desired artifact, exit the game and load it back.

I think this might be an accidental overlooking because usually bosses are hidden deeply from the save-reload entry points. This tactics works with "permadeath" as well.

In particular, this makes the Fleshband (250HP +5 all resistances) very easy to get. Also, since Vohn is high-level for this point of hero development, it's easy to get lots of XP and high-level artifacts as well.

Thoughts?

**Comment by vgaming** [comment]
Unrelated: am I right that Empyrean changed the amount of gold that heroes get in relation to HP/mana bottles? I'm easily going down to 0 gold in the new version, while in the earlier versions it was completely impossible.

If that's the case, then kudos for the change! It's really amazing, lost of concepts become saner if you don't have excessive gold.

P.S. I'd even reduce it 30% further (or increase cost of the things you really want to buy).

**Comment by dorkster** [comment]
Definitely an oversight. I'll make it so that Vohn doesn't respawn until the player enters the map from the proper entrance.

**Comment by dorkster** [comment]
>Unrelated: am I right that Empyrean changed the amount of gold that heroes get in relation to HP/mana bottles? I'm easily going down to 0 gold in the new version, while in the earlier versions it was completely impossible.

Not sure which version off the top of my head, but potion buy prices were changed at one point to scale with the player's level. At the same time, the sell prices were changed to a low flat value. Gold drop rates in general haven't changed for a very long time.

**Comment by vgaming** [comment]
I'm playing yesterday-s master branch now. Thanks for the explanation! I think it's a good change because the importance of just XP farming decreased a bit, and another non-discardable option started to exist.

And thanks for the Vohn fix as well! Awesome!

**Comment by vgaming** [comment]
It leads to a possibility to still buy potions/scrolls for cheap though, using the Shared stash. I'll raise a separate issue for that.
