### ISSUE TITLE
shared stash avoids incseased cost of potions/scrolls

### ISSUE THREAD

**Issue by vgaming** [flareteam/flare-game#801]
New versions of Flare have increased cost of consumables (potions/scrolls) as your level increases. The problem is that, unless you play permadeath, you can still transfer the money to a new level1 hero, buy the potions via this hero and put the potions to stash for the high-level hero to take. Basically buying these consumables cheaply.

It'd be nice if this approach could be somehow mitigated. Should we maybe disallow putting consumables (potions/scrolls) into stash? Or limit the number of items per slot in stash to 1, making exchanges impractical?

**Comment by dorkster** [comment]
I think being able to block such items from being put into the stash would be acceptable. We could add a `no_stash` flag to item properties, which we could set to true for Empyrean's consumables.

**Comment by vgaming** [comment]
Thanks for the fix!
