### ISSUE TITLE
Exiled Kingdoms - is it redone FlareRPG, or just uses public assets?

### ISSUE THREAD

**Issue by igorko** [flareteam/flare-game#805]
Found this game, http://www.exiledkingdoms.com/wiki/
It uses a lot of FlareRPG assets. Well, those assets are published on OpenGameArt and have different "free" licenses, but this game is commercial.

@clintbellanger as mostly assets are done by you, do you know something about that? Did enyone contact you?

Anyway you can notice a lot of game design elements are similar to Flare, so I have suspections...
Maybe someone has more info about this game?

Programming, concept, design, writing: David Ballestrino
http://exiledkingdoms.com/ek_credits.html

**Comment by dorkster** [comment]
AFAIK Exiled Kingdoms is its own entity. Clint's assets appear to be used within the license terms, and I believe the dev and Clint talked at one point to ensure the attribution was correct.

**Comment by qubodup** [comment]
Turns out EK is actually a Java application and uses libGDX.

Some info:
http://www.exiledkingdoms.com/forum/viewtopic.php?p=4616#p4616
http://www.exiledkingdoms.com/forum/viewtopic.php?t=10328
