### ISSUE TITLE
[Art request?] Alternate potions

### ISSUE THREAD

**Issue by dorkster** [flareteam/flare-game#808]
I've begun working on [expanding the alchemy system](https://github.com/dorkster/flare-game/commits/alchemy) by adding a new ingredient (mushrooms) and some new potions. I was able to source some mushrooms from the cave tileset with a few color alterations. But the new potions don't have icons. It would be great to have a few differently shaped bottles in a similar quality to @clintbellanger's [models](https://opengameart.org/content/health-and-mana-potion).

Just throwing this out there in case Clint or someone else wants to contribute. Though, I'll probably take a stab at it myself some time.

**Comment by clintbellanger** [comment]
This sounds fun. If you have some specific shape ideas let me know otherwise I'll just experiment.

**Comment by dorkster** [comment]
Finally got around to attempting this. Mine are of course based off of Clint's models/textures. I've added 4 new potion icons, seen in-game here with the new Mushroom ingredient:

![Screenshot_20200817_214415](https://user-images.githubusercontent.com/913982/90460957-10097d00-e0d3-11ea-8805-189f13e12990.png)

I tried to keep the silhouettes distinct for easy readability.

I've added the source files to the repo, but here's a quick look at the 256x256 renders:

![potion_1](https://user-images.githubusercontent.com/913982/90461083-61197100-e0d3-11ea-8dd2-ca541c55a5aa.png)
![potion_2](https://user-images.githubusercontent.com/913982/90461084-61197100-e0d3-11ea-8e89-a7b57036e0bc.png)
![potion_3](https://user-images.githubusercontent.com/913982/90461085-61197100-e0d3-11ea-9e42-631534f8d9d5.png)
![potion_4](https://user-images.githubusercontent.com/913982/90461086-61b20780-e0d3-11ea-9ac0-afd5a0a9be8d.png)
