### ISSUE TITLE
New animation exporter .blender script

### ISSUE THREAD

**Issue by yuriy-chumak** [flareteam/flare-game#811]
Hello. This is updated model exporting script (according to latest blender API changes). Scripts in source .blender files is too old and is not workable anymore.

```
import bpy
from math import radians
from os.path import join

S = bpy.context.scene
context = bpy.context

for i in range(1,9):
	# objects without parents should be parented to RenderPlatform
	bpy.data.objects['RenderPlatform'].rotation_euler.z = radians( -i * 360 / 8 )
	
	bpy.context.scene.render.filepath = join( bpy.path.abspath("//out"), "{a}-".format( a = i ) )
	bpy.ops.render.render( write_still = True, animation=True )
```

Thanks.

**Comment by yuriy-chumak** [comment]
Additionally, if anyone wants, the bash script to merge all exported images into one atlas:

```
#!/bin/bash

cd out

for i in $(seq 1 8); do
   convert $i-* +append $i.png
done
convert 1.png 2.png 3.png 4.png 5.png 6.png 7.png 8.png -append ../out.png
```

**Comment by dorkster** [comment]
It seems like the status of this script in our .blend files is a mixed bag. Some have a broken script, but some have an updated version which is nearly identical to the one you posted. I'll review the files in `art_src/` to see which need to be updated.

Slightly unrelated: I noticed something with spells like the fireball and the icicle. The rendering output for these doesn't match the ones that exist in game. These are old .blend files, so it's likely that changes to Blender over the years has affected how they work.
