### ISSUE TITLE
Find out author of Flare art asset

### ISSUE THREAD

**Issue by GamesOpenSource** [flareteam/flare-game#817]
Hello, while discussing asset origins at https://github.com/ooxi/violetland/issues/148 I wanted to use flare as an example for how to keep track of attribution/license info but came to realize that I can't find such information in FLARE.

Is there a way to find out the copyright information that relates to art asset files (author, possibly origin, possibly license if not flare-game/LICENSE.txt applies).

Thanks!

**Comment by dorkster** [comment]
[This wiki page](https://github.com/flareteam/flare-game/wiki/Credits) is probably the most detailed list of attribution we have.

**Comment by GamesOpenSource** [comment]
Ah, I knew flare had good art asset documentation, just had trouble finding it! thanks! :D
