### ISSUE TITLE
Question about Items

### ISSUE THREAD

**Issue by AdianAntilles** [flareteam/flare-game#825]
Hello Team!
I am currently in the stage every RPG-Gamer arrives one day: I grind the most difficult boss for loot. But it appears that only three different Underworld Items can drop. I have gotten 3 Underworld Blades, 2 Underworld Staffs and 2 Underworld Bows, but no other item drops.
That leads me to the question: Can other Underworld items drop? I would really appreciate some intel on this.
Greetz! AA

**Comment by dorkster** [comment]
Lezaith only drops the Underworld weapons. The armor pieces drop from the other bosses in the Underworld, Ogel and Rakk. Happy hunting!
