### ISSUE TITLE
Allow placing quest items in the player's private stash

### ISSUE THREAD

**Issue by dorkster** [flareteam/flare-game#827]
The engine [no longer](https://github.com/flareteam/flare-engine/commit/e18e1f6c0fe854a3630d6caaaf2211939ff7d56e) restricts quest items from being placed in the stash. I'd like to take advantage of this here, but there is some work to be done:

1. We should ensure that nothing breaks when the player is not carrying a quest item. Many cases use `requires_status` to check for the item, when `requires_item` would be more robust.
2. Dialog and quest text should reflect if the player has a relevant item or not.

**Comment by flarediablo** [comment]
I actually have a better solution:

Let the four figurines be always equipped. Each figurine has its own slot in the paper doll inventory. So if you get the bear figurine, it's as if your physical damage has been passively increased by 10 for the rest of the game. These bonuses stack on top of whatever accessory your character has equipped (belt, pendant, book).

As for the Gravebloom flower/ink quest items, Florin can help you to safekeep them. You already have to go to him everytime after obtaining a new quest item e.g. the quill. The NPC dialogue might have to be modified to reflect this.

The other quest items are mostly keys and in-dungeon notes, they are removed as you progress through the dungeon. So storing them in the stash isn't really necessary.
