### ISSUE TITLE
Bug with damage reflection

### ISSUE THREAD

**Issue by flarediablo** [flareteam/flare-game#828]
If an enemy is killed by a last hit caused by damage reflection, you do not get any experience from the 'kill', and you also do not get any loot.

Also, if the boss Seagate is killed by damage reflection, the two tombstones blocking the paths to the chests do not get destroyed. You would need to save and exit the game to restart at the staircase entrance.

Equip the full Saint Maria set which gives a 25% damage reflection to replicate this. I'm not sure if damage reflection scrolls produce a similar effect.

**Comment by dorkster** [comment]
Thank you for the report. This is now fixed: https://github.com/flareteam/flare-engine/commit/c91a53fbc30222a84eba212aa1e2a107698314e7
