### ISSUE TITLE
About translation contribute

### ISSUE THREAD

**Issue by bnk159hair** [flareteam/flare-game#831]
Hello, we are Korean university students. This project is an area we are interested in, so we would like to contribute.
We want to contribute through the Korean translation of the project. Is it okay to contribute?

**Comment by dorkster** [comment]
You are absolutely welcome to contribute! There are two ways you can submit translations:

1. Through Transifex ([Engine](https://www.transifex.com/flareorg/flare-engine/dashboard/) | [Game Data](https://www.transifex.com/flareorg/flare-game/dashboard/)). This is the preferred method.
2. Edit the translations locally with a tool like Poedit and submit them via pull request or email.
    - [Engine](https://github.com/flareteam/flare-engine/blob/master/mods/default/languages/)
    - [Game data: fantasycore](https://github.com/flareteam/flare-game/blob/master/mods/fantasycore/languages/)
    - [Game data: empyrean_campaign](https://github.com/flareteam/flare-game/blob/master/mods/empyrean_campaign/languages/)

**Comment by bnk159hair** [comment]
Thank you for your answer. My team will participate in the translation.

**Comment by dorkster** [comment]
I've merged your current work in to both the engine and game data.

How would you like to be credited? I currently have **bnk159hair** in the credits. But you mentioned that you were a group of students, so something else might be more appropriate.

**Comment by bnk159hair** [comment]
Please credit team name with member's name.
Our team name is 'Kor_OfenTHource'.
Our mamber's ID is bnk159hair, kangdonghun1230, HunSeongPark and paparad0x.

**Comment by dorkster** [comment]
Thanks. I've updated the credits accordingly.

I'll close this issue now, but will continue to merge any new translation work your team does.
