### ISSUE TITLE
Flare Empyrean Campaign Version 1.12 candidate 1

### ISSUE THREAD

**Issue by exkilho** [flareteam/flare-game#837]
Hi everyone, i was testing/playing F.E.C ver 1.12 candidate 1 and i was on Abandoned Mine on The Breach where the Antlion Burster level 6 are and they run directly to you and explode but after they explode if you mouse over them their status bar say its dead but they still run around has if they where alive i think its a bug.

**Comment by dorkster** [comment]
Thanks for the report. I can reproduce this, so I'll work on fixing it. Looks like a problem with the `requires_hp` Power property...

**Comment by exkilho** [comment]
Thank you and sorry to not put the labels or tags for the report but i just created this account to report the bug, and btw the mobs Antlion Sprayer when they attack they spray you ofc but they hit you multiple times, like the  red dmg text that appears on your character show multiple hits.  Did you guys made to act like that or i did discover an failure there? 
Thanks you and im loving the new implementations that the team already put on the game

**Comment by dorkster** [comment]
>Antlion Sprayer when they attack they spray you ofc but they hit you multiple times, like the red dmg text that appears on your character show multiple hits. Did you guys made to act like that or i did discover an failure there?

Yep. that's intentional. In 1.11, that text was even worse because it would overlap. In 1.12, it shouldn't overlap, plus we merge the damage numbers if they hit the same entity on the same frame (as is common with the spray attack).

>One more thing where i can go to to socialize and talk about the game where ppl are actively?

The most active place is probably the [forums on OGA](https://opengameart.org/forums/flare). The IRC isn't as active, but there's usually someone around. I *did* get your PM about this bug there earlier, but I felt it was better to give my response here.

**Comment by exkilho** [comment]
Oh ok, thank you for the fast response.
Btw i saw the new animation of slow by the ice dmg mobs but can you implement burning animation for the mobs that attack with fire dmg and while your char his on burning animation  the effect that makes in your char is the same as bleeding, i think that will be cool to but if its late to implement that forget about it...its just an hint.

**Comment by dorkster** [comment]
If we added a burn status effect, I would want it to be different from bleeding. Perhaps it could be a defense debuff? For the animation, it may be worth starting with the brazier tile from the dungeon tileset.

**Comment by exkilho** [comment]
Hmm makes sense, yeah the brazier tile i think its a good start.
