### ISSUE TITLE
[Full Screen Mode] UI is too large on a 1920x1080 resolution. (UI Text and controls are blury)

### ISSUE THREAD

**Issue by BoQsc** [flareteam/flare-game#839]
Windows 10 

It has some feel of bluriness on the text fonts and other UI controls.   
It would be great if we could scale User Interface down a little bit.   
The quality of gameplay would improve a lot.  

This image would not tell a lot from the first sight as it is quarter of a full size image.   
So I might suggest to open up image and look at it in full screen or play a game in full screen to notice the issue better.
![image](https://user-images.githubusercontent.com/21064622/127498262-175896af-27b0-4aea-bca8-748e48e712cc.png)

**Comment by dorkster** [comment]
The max render size that we use is 600 pixels tall. So if the window grows above that, scaling is to be expected. This limit is in place to keep amount of visible map fairly consistent for all players. But I'd be willing to bump it up to 768, which would be 1:1 with the ever common 1366x768 displays. 768 would also be a little less blurry when scaled up to 1080.

I think our assets are just too small to work well at 1080. *However*, you can change the max render size to whatever you want by editing `%APPDATA%\flare\config\settings.txt` and setting the value of `max_render_size`. Here are some screenshots with that value changed to 768 and 1080 for comparison:

![Screenshot_20210729_112807](https://user-images.githubusercontent.com/913982/127523062-362552c3-c9a5-4c74-840d-06cacac1b7c5.png)
![Screenshot_20210729_112831](https://user-images.githubusercontent.com/913982/127523067-c35f61a6-7960-4da2-ba82-96fb7d3b4f59.png)

**Comment by BoQsc** [comment]
> 768 would also be a little less blurry when scaled up to 1080.

That is true. But it is vastly better.  
The UI is almost perfect.  

### 1080 Monitor (1920x1080)
As you mention the camera of the game should be adjusted to zoom-in to the player more.
![image](https://user-images.githubusercontent.com/21064622/127538103-6389f959-9630-4bd0-9977-7618316b9394.png)
`max_render_size: 768` pixels 


Anyways, thanks for the information on tweaking.  
It is still very helpful.
