### ISSUE TITLE
[Feature Request] Adjust Stash container menu to be visually configurable (background image/colors scaled to fit space)

### ISSUE THREAD

**Issue by jasonkhanlar** [flareteam/flare-game#842]
re: https://github.com/flareteam/flare-game/issues/725

I tinkered with https://github.com/flareteam/flare-game/blob/master/mods/fantasycore/menus/stash.txt

```
# Settings for the Stash menu
# the first two values are x,y positions
# some items have two more values, width and height

#pos=0,0,320,416
pos=0,0,480,624
align=left
soundfx_open=soundfx/wood_open.ogg

label_title=160,8,center,top
#close=294,2
close=614,2
#currency=288,400,right,center
currency=608,816,right,center

slots_area=32,64
#stash_cols=8
stash_cols=16
#stash_rows=10
stash_rows=18
```

expecting the 80 slots to appear as 288 slots, and the user interface appears to work to handle it, but the visual background doesn't seem to scale to fit the ui area:

https://i.imgur.com/4QX9AIh.png

--- or did I miss something?

**Comment by jasonkhanlar** [comment]
I noticed https://github.com/flareteam/flare-engine/commit/d9adaaa133792f3dac6db45a60daa9dfaae9febc and added this to end of stash.txt (and reverting back to original values):

```
[tab]
name=Private

[tab]
name=Shared

[tab]
name=Rings
is_private=false

[tab]
name=Brute
is_private=false

[tab]
name=Scout
is_private=false

[tab]
name=Adept
is_private=false
```

and now it looks like the tabs do not fit contained in the menu https://i.imgur.com/4QgNNM9.png

**Comment by dorkster** [comment]
You would need to change [the image used for the stash menu](https://github.com/flareteam/flare-game/blob/master/mods/fantasycore/images/menus/stash.png).

This `art_src` folder of this repo contains a GIMP XCF file that can aid in editing the menu graphics: https://github.com/flareteam/flare-game/blob/master/art_src/interface/menus.xcf
