### ISSUE TITLE
Unique icon artwork for Super and Ultra potions

### ISSUE THREAD

**Issue by dorkster** [flareteam/flare-game#845]
I think we can just use the existing potion icons with some additional painted details (e.g. background glow).

**Comment by Danimal696** [comment]
There is actually a couple of unused potions models on the repository, i recovered one of them, the piramid looking one for my mod (copy paste icon if you want); the remaining one is a roundish looking one.

**Comment by dorkster** [comment]
![icons](https://user-images.githubusercontent.com/913982/146691766-e65d1473-d796-4f0b-b429-e42046e0aa64.png)

This is what I ended up with. I'm overall happy with them, but some details get lost when scaled down to 32x32. It might be worth toning down the glow effect on the middle tier.
