### ISSUE TITLE
Goblin Thief should be able to steal all kinds of potions

### ISSUE THREAD

**Issue by dorkster** [flareteam/flare-game#846]
As the title says. Especially with the new Super and Ultra potions, which the player will most likely be using by that point in the game.

**Comment by Danimal696** [comment]
Can i suggest a minor correction to the issue title?
Goblin Thief should be able to steal all **kinds of** potions

**Comment by Sturwandan** [comment]
Shouldn't killing the goblin thief make it drop the stolen potions?

**Comment by dorkster** [comment]
@Sturwandan Not really possible at the moment, since the goblin has no place to store the stolen potion(s). The current solution is to make the goblin's loot drop table favor potions. The goblin thief concept was made before I introduced the alchemy system, so I think adding ingredients/empty bottles to the drop table would be good as well. The player might not get back the exact potion that was stolen, but there's a good chance their supply will be recovered.
