### ISSUE TITLE
"Sacrifice" status is switched off after a defeat

### ISSUE THREAD

**Issue by tkzv** [flareteam/flare-game#902]
In the default Empyrean campaign after my character is killed in The Pit, and I choose "Continue", sometimes the "Sacrifice" icon disappears. Its bonuses no longer apply — MP regeneration seems to become considerably slower.

When I stop and restart the game, the icon is back.

Version 1.13, run from AppImage under Linux. I did not see this problem in 1.11.

Accidentally posted this bug to flare-engine as bug 1811

**Comment by dorkster** [comment]
Thanks for the report. It actually *was* an engine bug, so you posted to the right place initially.
Fixed here: https://github.com/flareteam/flare-engine/commit/dfa6d084ec7df0a54eb5e58c6c53f4e3332666b4
