### ISSUE TITLE
[Question] Is there any way to update translation of Flare Alpha (not by Pull Request on Github)

### ISSUE THREAD

**Issue by Blueberryy** [flareteam/flare-game#920]
Transifex project should get translation files of Flare Alpha

**Comment by dorkster** [comment]
Since the alpha_demo isn't being maintained/updated, it didn't make sense to include it in the flare-game project when setting up Transifex.

So I've set up a separate project just for the alpha_demo: https://www.transifex.com/flareorg/flare-game-alpha_demo/

**Comment by Blueberryy** [comment]
> Since the alpha_demo isn't being maintained/updated, it didn't make sense to include it in the flare-game project when setting up Transifex.
> 
> So I've set up a separate project just for the alpha_demo: https://www.transifex.com/flareorg/flare-game-alpha_demo/

Ah okay, i updated current Flare russian translation and wanted to do other stuff so thank you

**Comment by Blueberryy** [comment]
Hey uh, i can't see Alpha translation project but i sent request on assignment to Russian by your link :/ @dorkster

**Comment by dorkster** [comment]
Oops. I forgot to enable auto-accept for new contributors. You should be added now.
