### ISSUE TITLE
Android Flare Engine v1.14 APK showing as version 1.12

### ISSUE THREAD

**Issue by BRBsoup** [flareteam/flare-game#952]
In-game is shown properly, but the APK install package/android manifest info shows as "1.12"/"112"

**Comment by BRBsoup** [comment]
I think the APK being distributed was just built with the old manifest, as in the source code the manifest correctly shows 1.14/114

**Comment by dorkster** [comment]
Duplicate: https://github.com/flareteam/flare-engine/issues/1874
