### ISSUE TITLE
No more empty chests!

### ISSUE THREAD

**Issue by dorkster** [flareteam/flare-game#974]
It's very disappointing to get nothing from a chest. And when it does happen, it might seem like the game is broken.

I think we need some new loot tables for chests that guarantee, at the very least, gold.

I also think we should add a chance to get some of the "price-scaled" items that don't drop from enemies. These include potions, empty bottles, and scrolls.

**Comment by Blueberryy** [comment]
> It's very disappointing to get nothing from a chest. And when it does happen, it might seem like the game is broken.
> 
> I think we need some new loot tables for chests that guarantee, at the very least, gold.
> 
> I also think we should add a chance to get some of the "price-scaled" items that don't drop from enemies. These include potions, empty bottles, and scrolls.

Maybe it's bad idea but i'm gonna write it; What about automatically opening for crates without loot? Like your character near them and game will unpack them so you will not need to bother about clicking crate

**Comment by dorkster** [comment]
> Maybe it's bad idea but i'm gonna write it; What about automatically opening for crates without loot? Like your character near them and game will unpack them so you will not need to bother about clicking crate
> 
> Plus i think that empty crates is something that makes it a little realistic

I don't think whether or not the player has to interact with the chest is the core issue here. Plus, it would add complexity in terms of implementation, since we currently determine the loot to drop *after* the player interacts with an event that drops loot (i.e. a chest).

As for it being arguably more realistic, I would refer to [Gabe Newell's thoughts on the subject](https://www.youtube.com/watch?v=MGpFEv1-mAo). With how sparingly we place chests, I think it's a disservice to the player's actions for them to not contain *anything*.
