### ISSUE TITLE
Thank you for this amazing game!

### ISSUE THREAD

**Issue by KPCOFGS** [flareteam/flare-game#975]
Hi! I just finished the game, and I want to thank the team for this amazing game. It truly reminds me of the fun I had with single-player games back in the day. I may not have much knowledge to contribute to the repository, but expressing my appreciation is the least I can do. It's 2024, and there are still players discovering this nostalgic experience.

**Comment by Blueberryy** [comment]
> Hi! I just finished the game, and I want to thank the team for this amazing game. It truly reminds me of the fun I had with single-player games back in the day. I may not have much knowledge to contribute to the repository, but expressing my appreciation is the least I can do. It's 2024, and there are still players discovering this nostalgic experience👍

You can contribute into translation for some language if you know any other.
https://explore.transifex.com/flareorg/

But more than that it really is super free to play game, hope more people will find this game and contribute in code/translations.
